version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbeval
      MYSQL_USER: eval
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - esp_dbeval_net

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio@dmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9002:9000" #MinIO web interface
      - "9001:9001" #MinIO console
    networks:
      - esp_dbeval_net

  dbeval_be:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: dbeval_be
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/app  # Volume qui lie le répertoire local à /app dans le conteneur
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - minio
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio@dmin
      - AWS_STORAGE_BUCKET_NAME=documents
      - AWS_S3_ENDPOINT_URL=http://192.168.1.39:9002
      - AWS_LOCATION=exercises
      - DB_HOST=mysql
      - DB_NAME=dbeval
      - DB_USER=eval
      - DB_PASSWORD=userpassword
    networks:
      - esp_dbeval_net

networks:
  esp_dbeval_net:

volumes:
  mysql_data:
  minio_data:
